Fixes #227
mps-youtube/pafy pull request #237
Opened 2019-06-10 21:38 UTC by noembryo

Gets the stream's url from the `fragment_base_url` key only if the `url` key has the xml info.
I'm using it for almost a month now and I haven't found a not working link yet.

2020-01-04 23:46 UTC, kz6wk9 approved these changes
I'm using this too and this actually fix the issue

2020-01-07 14:18 UTC, vn-ki approved these changes
Did not verify, but if users say it works, it works, I guess.

2020-01-07 14:20 UTC, vn-ki commented
Is this fix still required @noembryo ?

2020-01-07 14:31 UTC, noembryo commented
> Is this fix still required @noembryo ?

Yes.
I just disabled the fix (in my local `pafy`) for my [test link](https://www.youtube.com/watch?v=qz1nlZb4MvM), and couldn't download it.

I use it in [an app](https://www.noembryo.com/apps.php?katalib) until this time, and no user has complained for missing any links, so it must work for them too...

2020-01-07 15:27 UTC, Deracinator commented
I tested and it seems that at least these 2 bugs were related to this issue:
https://github.com/mps-youtube/mps-youtube/issues/1000
https://github.com/mps-youtube/mps-youtube/issues/1031
The links provided didn't worked with the last version but after this commit, they do.

2020-01-08 10:58 UTC, ritiek commented
I made a similar PR (#230) which fixed fetching failing videos but had to be reverted since it broke pafy on other videos. A conditional seems to be a better choice like in this PR. But I haven't been keeping up with this lately so I'm not sure what the current state is regarding if YouTube API or youtube-dl has made any further changes regarding this. I'll check on this soon.

2020-01-09 05:32 UTC, ritiek commented
See the relevant issue on youtube-dl: https://github.com/ytdl-org/youtube-dl/issues/23324. We could use `--youtube-skip-dash-manifest` to get the direct URL on the command-line.

I think a better method to workaround this issue in pafy would be to default to above youtube-dl option. We could do this by appending [`{youtube_include_dash_manifest': False}`](https://github.com/ytdl-org/youtube-dl/blob/3e4cedf9e8cd3157df2457df7274d0c842421945/youtube_dl/YoutubeDL.py#L309-L312) in [g.py](https://github.com/mps-youtube/pafy/blob/7b9fc862e5a46755a96bcf2845b1f68b61e8f29d/pafy/g.py#L30).

@noembryo What do you think?

2020-01-09 05:37 UTC, ritiek requested changes
Left a comment.

2020-01-09 09:38 UTC, noembryo commented
@ritiek Just tried to add the `{'youtube_include_dash_manifest': False}` to `def_ydl_opts` in `g.py` and removed my fix.
It doesn't work with my test link.
Do I miss something obvious?

2020-01-09 10:57 UTC, shibotto commented
I only did a brief test with a couple of videos that have been giving me troubles (same as mps-youtube/mps-youtube#1000), but both solutions work equally fine on my end. The test link @noembryo provided works for me despite the workarounds, so I can't test it, sorry.

Using mps-youtube it was not immediately obvious to me that I had to delete `.config/mps-youtube/cache_py_*` to (I think?) fetch new URLs.

2020-01-09 12:13 UTC, ritiek commented
@noembryo Seems all right to me. I don't really see why that doesn't seem to work for you. It seems to be working fine on my end. I tried a couple of videos on this code:
```python
import pafy

url = "https://www.youtube.com/watch?v=p9K0bSeKPZY"
v = pafy.new(url)

for s in v.videostreams:
    print(s.url)

for s in v.audiostreams:
    print(s.url)
```
And all of the URLs link directly to the media URL.

2020-01-09 12:39 UTC, noembryo commented
@ritiek does my test link works for you?

2020-01-09 13:12 UTC, noembryo commented
@ritiek this does not work
```python
import pafy

url = "https://www.youtube.com/watch?v=qz1nlZb4MvM"
v = pafy.new(url)

for s in v.videostreams:
    print(s.url)

for s in v.audiostreams:
    print(s.url)
```

2020-01-09 13:27 UTC, ritiek commented
> @ritiek this does not work

Does the code not output any URLs or simply errors out?

@noembryo Yes, I can download the audio from your test link with or without applying the fix.
```python
import pafy

url = "https://www.youtube.com/watch?v=qz1nlZb4MvM"
v = pafy.new(url)
audio = v.getbestaudio()
audio.download()
```

> The test link @noembryo provided works for me despite the workarounds

Seems like I'm getting the same results as @shibotto.

I'm not really sure but could this be something related to location from where YouTube is accessed?

How does https://www.youtube.com/watch?v=-44SUxonfSc work for you? This one outputs manifest URLs for me when no fix is applied, with this code:
```python
import pafy

url = "https://www.youtube.com/watch?v=-44SUxonfSc"
v = pafy.new(url)
for s in v.audiostreams:
    print(s.url)
```

2020-01-09 13:33 UTC, noembryo commented
> > @ritiek this does not work
> 
> Does the code not output any URLs or simply errors out?

Prints a series of `None`

> @noembryo Yes, I can download the audio from your test link with or without applying the fix.
> 
> ```python
> import pafy
> 
> url = "https://www.youtube.com/watch?v=qz1nlZb4MvM"
> v = pafy.new(url)
> audio = v.getbestaudio()
> audio.download()
> ```
> 
> > The test link @noembryo provided works for me despite the workarounds
> 
> Seems like I'm getting the same results as @shibotto.
> 
> I'm not really sure but could this be something related to location from where YouTube is accessed?

Could be this. Either way..

> How does https://www.youtube.com/watch?v=-44SUxonfSc work for you? This one outputs manifest URLs for me when no fix is applied, with this code:
> 
> ```python
> import pafy
> 
> url = "https://www.youtube.com/watch?v=-44SUxonfSc"
> v = pafy.new(url)
> for s in v.audiostreams:
>     print(s.url)
> ```
This works without the fix.
Audio & video stream links.

2020-01-09 13:41 UTC, ritiek commented
This is really weird. We seem to be getting completely opposite results. What version of youtube-dl are you on?

Mine is:
```python
>>> import youtube_dl
>>> youtube_dl.version.__version__
'2020.01.01'
```

2020-01-09 13:42 UTC, noembryo commented
2020.1.1 too..

2020-01-09 13:44 UTC, noembryo commented
Maybe location _is_ a serious factor..

2020-01-09 13:47 UTC, ritiek commented
I see. I'll tag other members but otherwise I guess we could merge your original PR since it's at least consistent for both of us.

2020-01-10 08:54 UTC, vn-ki approved these changes
This looks like a harmless change. So I'll approve.

2020-01-10 13:35 UTC, ritiek approved these changes
Ok then! Let's merge this in. Thanks a lot @noembryo!

2020-01-10 13:37 UTC, noembryo commented
> Ok then! Let's merge this in. Thanks a lot @noembryo!

Thank _you all_ for pafy! ;o)

2020-01-10 13:37 UTC, merged